### ISSUE TITLE
Please add a License

### ISSUE THREAD

**Issue by rfzeg** [marcovc41/vision_tools#3]
Hello Marco,

Thank you for sharing this repository on GitHub. I would like to test your code and maybe use it for educational purposes and training other students. Unfortunately your repository is lacking a license.
Could you please add a license file to this repository?
Most people place their license text in a file named LICENSE.txt (or LICENSE.md) in the root of the repository.
More info here: https://help.github.com/articles/adding-a-license-to-a-repository/

Best regards,

Roberto

**Comment by mvaldezc** [comment]
Hello Roberto,

Sorry for the delay, I was inactive for some time on github but finally added a licence to the project. I'll be more active, so please feel free to use my code and contact me if you have any issue.

Best regards,
Marco
